// Reads a Trace-generated PDF and extracts the embedded TRACE_REPORT_V1
// payload from its Keywords metadata. Only Trace-format PDFs are supported.

import { PDFDocument } from "pdf-lib";

export interface TraceReportEntry {
  id?: string;
  entry_date?: string | null;
  start_time?: string | null;
  end_time?: string | null;
  duration_minutes?: number | null;
  hourly_rate?: number | null;
  billable?: boolean | null;
  project_name?: string | null;
  task_name?: string | null;
  notes?: string | null;
  // … plus any other fields snapshot at export time
  [k: string]: unknown;
}

export interface TraceReportPayload {
  v: number;
  worker: { name: string | null; email: string | null };
  client: { name: string };
  period_start: string;
  period_end: string;
  currency: string;
  total_hours: number;
  total_amount: number;
  shared_columns: string[];
  entries: TraceReportEntry[];
}

const MARKER = "TRACE_REPORT_V1:";

const decodeBase64Json = (b64: string): TraceReportPayload => {
  let bin: string;
  if (typeof window !== "undefined" && typeof window.atob === "function") {
    bin = window.atob(b64);
  } else {
    bin = Buffer.from(b64, "base64").toString("binary");
  }
  // Reverse the unescape(encodeURIComponent(...)) trick used on write.
  const utf8 = decodeURIComponent(
    Array.from(bin)
      .map((c) => "%" + c.charCodeAt(0).toString(16).padStart(2, "0"))
      .join(""),
  );
  return JSON.parse(utf8);
};

export class TraceImportError extends Error {}

export async function parseTraceReportFile(file: File): Promise<TraceReportPayload> {
  if (!/\.pdf$/i.test(file.name) && file.type !== "application/pdf") {
    throw new TraceImportError("Please choose a Trace PDF report.");
  }
  const bytes = new Uint8Array(await file.arrayBuffer());
  let pdf: PDFDocument;
  try {
    pdf = await PDFDocument.load(bytes, { ignoreEncryption: true });
  } catch {
    throw new TraceImportError("That file isn't a readable PDF.");
  }

  const keywords = pdf.getKeywords() ?? "";
  const idx = keywords.indexOf(MARKER);
  if (idx === -1) {
    throw new TraceImportError(
      "This PDF doesn't contain a Trace payload. Ask the freelancer to share a report generated by the current version of Trace.",
    );
  }
  const b64 = keywords.slice(idx + MARKER.length).trim();
  let payload: TraceReportPayload;
  try {
    payload = decodeBase64Json(b64);
  } catch {
    throw new TraceImportError("Couldn't read the Trace payload — the file may be corrupted.");
  }
  if (payload?.v !== 1 || !Array.isArray(payload.entries)) {
    throw new TraceImportError("Unsupported Trace report version.");
  }
  return payload;
}
